#!/usr/bin/env python

import os
import sys
import json
import glob
import random
import argparse
from os.path import join as pjoin

import textworld
from textworld.agents import HumanAgent

import gym
import textworld.gym

from alfworld.info import ALFWORLD_DATA
import alfworld.gen
from alfworld.agents.utils.misc import Demangler, get_templated_task_desc, clean_alfred_facts, add_task_to_grammar


class AlfredDemangler(textworld.core.Wrapper):

    def load(self, *args, **kwargs):
        super().load(*args, **kwargs)

        demangler = Demangler(game_infos=self._game.infos)
        for info in self._game.infos.values():
            info.name = demangler.demangle_alfred_name(info.id)


def main(args):
    # register a new Gym environment.
    infos = textworld.EnvInfos(
        won=True,
        admissible_commands=True)
    env_id = textworld.gym.register_game(args.problem, infos,
                                         max_episode_steps=1000000,
                                         wrappers=[AlfredDemangler])

    # reset env
    env = gym.make(env_id)
    obs, infos = env.reset()

    # human agent
    agent = HumanAgent(True)
    agent.reset(env)

    while True:
        print(obs)
        print(infos)
        cmd = agent.act(infos, 0, False)
        obs, score, done, infos = env.step(cmd)

        if done:
            print("You won!")
            break


if __name__ == "__main__":
    description = "Play the abstract text version of an ALFRED environment."
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("problem", nargs="?", default=None,
                        help="Path to a folder containing PDDL and traj_data files."
                             f"Default: pick one at random found in {ALFWORLD_DATA}")
    args = parser.parse_args()
    main(args)
