---
model_creator: "TransformerGenDQN"
num_tokens: 500
num_turns: 6
batch_size: 32
save_gap_t: 10000
embedding_size: 64
learning_rate: 5e-5
tokenizer_type: "Bert"
n_tokens_per_action: 20
max_decoding_size: 20
max_snapshot_to_keep: 100
eval_episode: 5
game_episode_terminal_t: 100
replay_mem: 100000
collect_floor_plan: True