---
# for the legacy CNN DRRN

model_creator: "LegacyCnnDRRN"
num_tokens: 1000
num_turns: 5
batch_size: 32
save_gap_t: 10000
embedding_size: 64
learning_rate: 5e-5
num_conv_filters: 32
tokenizer_type: NLTK
max_snapshot_to_keep: 10
eval_episode: 2
game_episode_terminal_t: 100
replay_mem: 100000
collect_floor_plan: True
annealing_eps_t: 2000000
observation_t: 10000
init_eps: 1.0
start_t_ignore_model_t: False  # set to False unless do curriculum learning
use_step_wise_reward: True
agent_clazz: BaseAgent  # original model uses CompetitionAgent
