---
# for the legacy CNN DRRN

model_creator: CnnDRRN
core_clazz: DRRNCore
agent_clazz: ZorkAgent
num_tokens: 1000
num_turns: 10
batch_size: 32
save_gap_t: 5000
embedding_size: 64
learning_rate: 1e-5
num_conv_filters: 32
tokenizer_type: NLTK
max_snapshot_to_keep: 10
eval_episode: 2
game_episode_terminal_t: 350
replay_mem: 50000
collect_floor_plan: False
annealing_eps_t: 2000000
observation_t: 1000
init_eps: 1.0
final_eps: 5e-2
start_t_ignore_model_t: False  # set to False unless do curriculum learning
use_step_wise_reward: False
policy_to_action: EPS
policy_eps: 5e-2
action_padding_in_tj: True
append_objective_to_tj: False
gamma: 1.0
walkthrough_guided_exploration: True
prob_complete_walkthrough: 0.8
