---
# for Transformer DRRN

model_creator: TransformerDSQN
num_tokens: 256
num_turns: 5
batch_size: 32
save_gap_t: 5000
embedding_size: 64
learning_rate: 5e-5
tokenizer_type: BERT
max_snapshot_to_keep: 100
eval_episode: 5
game_episode_terminal_t: 100
replay_mem: 500000  # 500k
collect_floor_plan: True
agent_clazz: DSQNCompetitionAgent
core_clazz: DSQNCore
learner_clazz: null  # unimplemented DSQNLearner
annealing_eps_t: 10000000  # 10 million
observation_t: 10000
init_eps: 1.0
start_t_ignore_model_t: False  # set to False unless do curriculum learning
use_step_wise_reward: True
policy_to_action: LinUCB
